[project]
name = "gemstone-price-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair==4.2.2",
    "catboost>=1.2.10",
    "dill>=0.4.1",
    "fastapi>=0.132.0",
    "ipykernel>=7.2.0",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "pandas>=3.0.1",
    "pydantic>=2.12.5",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
    "standard-imghdr>=3.13.0",
    "streamlit>=1.19.0",
    "uvicorn>=0.41.0",
    "xgboost>=3.2.0",
]
